//
// Generated by Microsoft (R) D3DX9 Shader Compiler 4.09.00.1247
//
//   fxc /T vs_1_1 /E VS /Fc ColorNOneTexture.vsh ColorNOneTexture.fx
//
//
// Parameters:
//
//   float4x4 matWorldViewProj;
//
//
// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   matWorldViewProj c8       4
//

    vs_1_1
    dcl_position v0
    dcl_texcoord v7
    dp4 oPos.x, v0, c8
    dp4 oPos.y, v0, c9
    dp4 oPos.z, v0, c10
    dp4 oPos.w, v0, c11
    mov oT0.xy, v7

// approximately 5 instruction slots used
