//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /nologo /T vs_1_1 /E VS /Fc
//    D:\game-development\workspace\active\gameversity-advanced-rendeering-class\final-project-character-engine\shaders\ColorNOneTexture.vsh
//    D:\game-development\workspace\active\gameversity-advanced-rendeering-class\final-project-character-engine\shaders\ColorNOneTexture.fx
//
//
// Parameters:
//
//   float4 fFarNear;
//   float4x4 matLightViewProj;
//   float4x4 matLightViewProjTexAdj;
//   float4x4 matWorldViewProj;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   matWorldViewProj       c8       4
//   matLightViewProj       c16      4
//   matLightViewProjTexAdj c20      4
//   fFarNear               c34      1
//

    vs_1_1
    def c0, 2.079, 0, 0, 0
    dcl_position v0
    dcl_texcoord v7
    dp4 oPos.x, v0, c8
    dp4 oPos.y, v0, c9
    dp4 oPos.z, v0, c10
    dp4 oPos.w, v0, c11
    dp4 oT1.x, v0, c20
    dp4 oT1.y, v0, c21
    dp4 oT1.z, v0, c22
    dp4 oT1.w, v0, c23
    dp4 r0.x, v0, c18
    add r0.x, r0.x, c34.y
    add r0.y, -c34.y, c34.x
    rcp r0.y, r0.y
    mul r0.x, r0.y, r0.x
    dp4 r0.y, v0, c19
    mad oT2.x, r0.x, -r0.y, c0.x
    mov oT0.xy, v7

// approximately 16 instruction slots used
