//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /nologo /T vs_1_1 /E VS /Fc
//    D:\game-development\workspace\active\gameversity-advanced-rendeering-class\final-project-character-engine\shaders\CreateShadowMap.vsh
//    D:\game-development\workspace\active\gameversity-advanced-rendeering-class\final-project-character-engine\shaders\CreateShadowMap.fx
//
//
// Parameters:
//
//   float4 fFarNear;
//   float4x4 mLightViewProj;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   mLightViewProj c16      4
//   fFarNear       c34      1
//

    vs_1_1
    dcl_position v0
    dp4 oPos.x, v0, c16
    dp4 oPos.y, v0, c17
    add r0.x, -c34.y, c34.x
    rcp r0.x, r0.x
    dp4 r0.z, v0, c18
    add r0.y, r0.z, c34.y
    mul r0.x, r0.x, r0.y
    dp4 r0.w, v0, c19
    mul oT0.x, r0.w, -r0.x
    mov oPos.zw, r0

// approximately 10 instruction slots used
