//
// Generated by Microsoft (R) D3DX9 Shader Compiler 4.09.00.1126
//
//   fxc /T vs_1_1 /E VS /Fc shaders/CreateShadowMap.vsh
//    d:\classes\advanced rendering\FinalProjectCharacterEngine\shaders\CreateShadowMap.fx
//
//
// Parameters:
//
//   float4 fFarNear;
//   float4x4 mLightViewProj;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   mLightViewProj c16      4
//   fFarNear       c34      1
//

    vs_1_1
    dcl_position v0
    dp4 oPos.x, v0, c16
    dp4 oPos.y, v0, c17
    add r0.w, -c34.y, c34.x
    rcp r1.w, r0.w
    dp4 r0.y, v0, c18
    add r0.w, r0.y, c34.y
    mov oPos.z, r0.y
    mul r0.w, r1.w, r0.w
    dp4 r0.x, v0, c19
    mul oT0.x, -r0.w, r0.x
    mov oPos.w, r0.x

// approximately 11 instruction slots used
