//
// Generated by Microsoft (R) D3DX9 Shader Compiler 4.09.00.1247
//
//   fxc /T vs_1_1 /E VS /Fc diffspec.vsh diffuseSpecular.fx
//
//
// Parameters:
//
//   float4 LightDir;
//   float4x4 matWorld;
//   float4x4 matWorldViewProj;
//   float4 vecEye;
//
//
// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   matWorld         c0       4
//   matWorldViewProj c8       4
//   LightDir         c12      1
//   vecEye           c24      1
//

    vs_1_1
    dcl_position v0
    dcl_normal v3
    dcl_texcoord v7
    dcl_tangent v8
    dp4 oPos.x, v0, c8
    dp4 oPos.y, v0, c9
    dp4 r0.w, v0, c3
    dp4 r0.x, v0, c0
    dp4 r0.y, v0, c1
    dp4 r0.z, v0, c2
    dp4 oPos.z, v0, c10
    dp4 r0.w, r0, r0
    dp4 oPos.w, v0, c11
    rsq r0.w, r0.w
    mad r2.xyz, r0, -r0.w, c12
    mad r1.xyz, r0, -r0.w, c24
    dp3 r3.x, v8, c0
    dp3 r3.y, v8, c1
    dp3 r3.z, v8, c2
    mov r0.xyz, v8
    mul r4.xyz, r0.zxyw, v3.yzxw
    dp3 oT2.x, r3, -r2
    mad r0.xyz, r0.yzxw, v3.zxyw, -r4
    dp3 oT1.x, r3, r1
    dp3 r3.x, r0, c0
    dp3 r3.y, r0, c1
    dp3 r3.z, r0, c2
    dp3 oT2.y, r3, -r2
    dp3 r0.x, v3, c0
    dp3 r0.y, v3, c1
    dp3 r0.z, v3, c2
    dp3 oT1.y, r3, r1
    dp3 oT2.z, r0, -r2
    dp3 oT1.z, r0, r1
    mov oT0.xy, v7

// approximately 31 instruction slots used
