//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /nologo /T vs_1_1 /E VS /Fc
//    D:\game-development\workspace\active\gameversity-advanced-rendeering-class\final-project-character-engine\shaders\diffuseSpecular.vsh
//    D:\game-development\workspace\active\gameversity-advanced-rendeering-class\final-project-character-engine\shaders\diffuseSpecular.fx
//
//
// Parameters:
//
//   float4 LightDir;
//   float4 fFarNear;
//   float4x4 matLightViewProj;
//   float4x4 matLightViewProjTexAdj;
//   float4x4 matWorld;
//   float4x4 matWorldViewProj;
//   float4 vecEye;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   matWorld               c0       4
//   matWorldViewProj       c8       4
//   LightDir               c12      1
//   matLightViewProj       c16      4
//   matLightViewProjTexAdj c20      4
//   vecEye                 c24      1
//   fFarNear               c34      1
//

    vs_1_1
    def c4, 2.079, 0, 0, 0
    dcl_position v0
    dcl_normal v3
    dcl_texcoord v7
    dcl_tangent v8
    dp4 oPos.x, v0, c8
    dp4 oPos.y, v0, c9
    dp4 oPos.z, v0, c10
    dp4 oPos.w, v0, c11
    dp4 r0.w, v0, c3
    dp4 r0.x, v0, c0
    dp4 r0.y, v0, c1
    dp4 r0.z, v0, c2
    dp4 r0.w, r0, r0
    rsq r0.w, r0.w
    mad r1.xyz, r0, -r0.w, c12
    mad r0.xyz, r0, -r0.w, c24
    dp3 r2.x, v8, c0
    dp3 r2.y, v8, c1
    dp3 r2.z, v8, c2
    dp3 oT2.x, r2, -r1
    dp3 oT1.x, r2, r0
    mov r2.xyz, v8
    mul r3.xyz, r2.zxyw, v3.yzxw
    mad r2.xyz, r2.yzxw, v3.zxyw, -r3
    dp3 r3.x, r2, c0
    dp3 r3.y, r2, c1
    dp3 r3.z, r2, c2
    dp3 oT2.y, r3, -r1
    dp3 oT1.y, r3, r0
    dp3 r2.x, v3, c0
    dp3 r2.y, v3, c1
    dp3 r2.z, v3, c2
    dp3 oT2.z, r2, -r1
    dp3 oT1.z, r2, r0
    dp4 oT3.x, v0, c20
    dp4 oT3.y, v0, c21
    dp4 oT3.z, v0, c22
    dp4 oT3.w, v0, c23
    dp4 r0.x, v0, c18
    add r0.x, r0.x, c34.y
    add r0.y, -c34.y, c34.x
    rcp r0.y, r0.y
    mul r0.x, r0.y, r0.x
    dp4 r0.y, v0, c19
    mad oT4.x, r0.x, -r0.y, c4.x
    mov oT0.xy, v7

// approximately 42 instruction slots used
