//
// Generated by Microsoft (R) D3DX9 Shader Compiler 4.09.00.1247
//
//   fxc /T vs_1_1 /E VS /Fc diffuse.vsh diffuse.fx
//
//
// Parameters:
//
//   float4 LightDir;
//   float4x4 matWorld;
//   float4x4 matWorldViewProj;
//
//
// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   matWorld         c0       4
//   matWorldViewProj c8       4
//   LightDir         c12      1
//

    vs_1_1
    def c4, 0.5, 0, 0, 0
    dcl_position v0
    dcl_normal v3
    dcl_texcoord v7
    dcl_tangent v8
    dp4 r0.w, v0, c3
    dp4 r0.x, v0, c0
    dp4 r0.y, v0, c1
    dp4 r0.z, v0, c2
    dp4 r0.w, r0, r0
    mov r1.xyz, v8
    mul r2.xyz, r1.zxyw, v3.yzxw
    rsq r0.w, r0.w
    mad r1.xyz, r1.yzxw, v3.zxyw, -r2
    mad r2.xyz, r0, -r0.w, c12
    dp3 r0.x, r1, c0
    dp3 r0.y, r1, c1
    dp3 r0.z, r1, c2
    dp3 r0.y, r0, -r2
    dp3 r3.x, v8, c0
    dp3 r3.y, v8, c1
    dp3 r3.z, v8, c2
    dp3 r1.x, v3, c0
    dp3 r1.y, v3, c1
    dp3 r1.z, v3, c2
    dp3 r0.x, r3, -r2
    dp3 r0.z, r1, -r2
    dp4 oPos.x, v0, c8
    dp3 r1.x, r0, r0
    dp4 oPos.y, v0, c9
    rsq r0.w, r1.x
    dp4 oPos.z, v0, c10
    mul r0.xyz, r0, r0.w
    dp4 oPos.w, v0, c11
    mad oD0.xyz, r0, c4.x, c4.x
    mov oT0.xy, v7
    mov oT1.xy, v7

// approximately 32 instruction slots used
