//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//   fxc /nologo /T vs_1_1 /E VS /Fc
//    D:\game-development\workspace\active\gameversity-advanced-rendeering-class\final-project-character-engine\shaders\Sphere.vsh
//    D:\game-development\workspace\active\gameversity-advanced-rendeering-class\final-project-character-engine\shaders\Sphere.fx
//
//
// Parameters:
//
//   float4 SphereColor;
//   float4x4 matWorldViewProj;
//
//
// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   matWorldViewProj c0       4
//   SphereColor      c4       1
//

    vs_1_1
    dcl_position v0
    dp4 oPos.x, v0, c0
    dp4 oPos.y, v0, c1
    dp4 oPos.z, v0, c2
    dp4 oPos.w, v0, c3
    mov oD0, c4

// approximately 5 instruction slots used
