//
// Generated by Microsoft (R) D3DX9 Shader Compiler 4.09.00.1247
//
//   fxc /T vs_1_1 /E VS /Fc Sphere.vsh Sphere.fx
//
//
// Parameters:
//
//   float4 SphereColor;
//   float4x4 matWorldViewProj;
//
//
// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   matWorldViewProj c0       4
//   SphereColor      c4       1
//

    vs_1_1
    dcl_position v0
    dp4 oPos.x, v0, c0
    dp4 oPos.y, v0, c1
    dp4 oPos.z, v0, c2
    dp4 oPos.w, v0, c3
    mov oD0, c4

// approximately 5 instruction slots used
